spring:
  profiles: default
  pid:
    file: review.pid

# Strongly recommend to set this property to "none" in a production environment!
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000


server:
  port: 7003

logging:
  level:
    root: INFO
---
spring:
  profiles: docker
  pid:
    file: review.pid
server:
  port: 8080

logging:
  level:
    root: INFO
