spring:
  profiles: default
  pid:
    file: review.pid
# Strongly recommend to set this property to "none" in a production environment!
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000
  cloud:
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        input:
          destination: reviews
          group: reviewsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 7003

logging:
  level:
    root: INFO
---
spring:
  profiles: docker
  pid:
    file: review.pid
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: user
    password: pwd
  hikari:
    initializationFailTimeout: 60000
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka

server:
  port: 8080

logging:
  level:
    root: INFO
