spring:
  profiles: default
  pid:
    file: product.pid
  data:
  mongodb:
    host: localhost
    port: 27017
    database: product-db

server:
  port: 7001

logging:
  level:
    root: INFO
---
spring:
  profiles: docker
  pid:
    file: product.pid
server:
  port: 8080

spring.data.mongodb.host: mongodb

logging:
  level:
    root: INFO
